version: 0.5.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: x86
clone_depth: 1
clone_folder: c:\src\
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore src\
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: setup\build.bat
test:
  categories:
    except:
    - Local
artifacts:
- path: setup\Output\*.exe
deploy: off
