# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/AppGet.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: recursive

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.x'
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    maximumCpuCount: true

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
#     testSelector: 'testAssemblies'
#     testAssemblyVer2: |
#       **\\AppGet.Manifest.Tests.dll
#       !**\*TestAdapter.dll
#       !**\obj\** 
#     otherConsoleOptions: '/Framework:.NETCoreApp,Version=v2.2'
#     runInParallel: true

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*tests.dll |
      !**\netcoreapp*\*.* |
      !**\*TestAdapter.dll |
      !**\obj\** 
    otherConsoleOptions: '/Framework:.NETFramework,Version=v4.6.1'
    runInParallel: true